version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: caremonitor-bd
      MYSQL_USER: master
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--max_allowed_packet=128M"
    ports:
      - "3306:3306"
